# Menjalankan seluruh proses: kompilasi lalu eksekusi program
run: build
    ./demo

# Melakukan kompilasi kode C menjadi file aplikasi
build:
    gcc -Wall -Wextra *.c -lm -o demo

# Menghapus file hasil kompilasi (bersih-bersih)
clean:
    rm -f demo
